---

- hosts: controlplane
  gather_facts: no
  become: false
  tasks:
  - name: Applying machines’ configuration | Setting facts
    set_fact:
      talosctl_opts: --insecure --talosconfig ../../talosconfig  -n {{ inventory_hostname }}

  - name: Applying machines’ configuration | Controlplane
    delegate_to: localhost
    ansible.builtin.command: talosctl apply-config {{ talosctl_opts }} --file ../../controlplane.yaml

- hosts: worker
  gather_facts: no
  become: false
  tasks:
  - name: Applying machines’ configuration | Setting facts
    set_fact:
      talosctl_opts: --insecure --talosconfig ../../talosconfig  -n {{ inventory_hostname }}

  - name: Applying machines’ configuration | Workers
    delegate_to: localhost
    ansible.builtin.command: talosctl apply-config {{ talosctl_opts }} --file ../../worker.yaml
