###############################################################################
# Controlplane

- hosts: controlplane
  gather_facts: no
  become: false
  serial: 1

  vars:
    generic_machineconfig: controlplane.yaml

  tasks:
  - name: Applying configuration | Including tasks
    include_tasks: '{{ inventory_dir }}/tasks/apply-host-conf.yml'

###############################################################################
# Worker

- hosts: worker
  gather_facts: no
  become: false
  serial: 1

  vars:
    generic_machineconfig: worker.yaml

  tasks:
  - name: Applying configuration | Including tasks
    include_tasks: '{{ inventory_dir }}/tasks/apply-host-conf.yml'
