- hosts: controlplane
  gather_facts: no
  become: false
  serial: 1

  tasks:
  - name: Applying configuration | Check if the cluster has already been bootstrapped
    delegate_to: localhost
    run_once: true
    register: kube_context
    failed_when: false
    changed_when: false
    ansible.builtin.shell: |
      kubectl config get-contexts | awk '{print $1,$3}' | fgrep '* {{ cluster_name }}'

  - name: Applying configuration | Check if the cluster has already been bootstrapped
    assert:
      that: kube_context.stdout_lines | length == 0
      fail_msg: |
        The cluster has already been deployed. Switch to '../day-2' operations directory and use 'add-nodes' target.

  - name: Applying configuration | Including tasks
    include_tasks: '{{ inventory_dir }}/tasks/gen-host-conf.yml'

  - name: Applying configuration | Including tasks
    include_tasks: '{{ inventory_dir }}/tasks/apply-host-conf.yml'
