---

- hosts: controlplane
  gather_facts: no
  become: false
  run_once: true
  tasks:
  - name: MetalLB | Define facts
    set_fact:
      metallb_crd: ../manifests/metallb-native.yaml
      metallb_addresses: ../manifests/metallb-layer2.yaml
      ipaddr_pool: "{{ metallb_l2_ipaddr_pool | split(',') }}"

  - name: MeltalLB | Check the required variables
    assert:
      fail_msg: A pool of IP addresses is required
      that:
      - metallb_l2_ipaddr_pool is defined
      - metallb_l2_ipaddr_pool is iterable
      - ipaddr_pool | length > 0
      - ipaddr_pool[0] != ""
      - ipaddr_pool_name is defined
      - ipaddr_pool_name | length > 5

  - name: MeltalLB | Download the operator
    delegate_to: localhost
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/metallb/metallb/v0.14.3/config/manifests/metallb-native.yaml
      dest: "{{ metallb_crd }}"
      mode: '0664'

  - name: MeltalLB | Deploy the operator
    delegate_to: localhost
    kubernetes.core.k8s:
      state: present
      src: "{{ metallb_crd }}"

  - name: MeltalLB | Configure IPAddressPool and L2Advertisement
    delegate_to: localhost
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', metallb_addresses) | from_yaml }}"
