- hosts: worker
  gather_facts: no
  become: false
  tasks:
  - name: Applying machines’ configuration | Setting facts
    set_fact:
      talosctl_opts: --talosconfig ../../talosconfig  -n {{ inventory_hostname }} -e {{ inventory_hostname }}
      talosctl_patch_opts: --mode=no-reboot machineconfig --patch @../patchs/openebs-kubelet.yaml

  - name: Applying machines’ configuration | Workers
    register: patch
    delegate_to: localhost
    changed_when: patch.stderr | regex_search("no changes detected.") != None
    ansible.builtin.command: talosctl {{ talosctl_opts }} patch {{ talosctl_patch_opts }}