- hosts: all
  gather_facts: no
  become: false
  serial: 1
  tasks:
  - name: Reboot | Set facts
    set_fact:
      talosctl_opts: --talosconfig={{ inventory_dir }}/talosconfig  -n {{ ansible_host | default(inventory_hostname) }} --endpoints {{ ansible_host | default(inventory_hostname) }}

  - name: Reboot | Reboot the cluster
    delegate_to: localhost
    ansible.builtin.command: talosctl {{ talosctl_opts }} reboot
