- hosts: all
  gather_facts: no
  become: false
  tasks:
  - name: Shutdown | Set facts
    set_fact:
      talosctl_opts: --talosconfig={{ inventory_dir }}/talosconfig  -n {{ ansible_host | default(inventory_hostname) }} -e {{ ansible_host | default(inventory_hostname) }}

  - name: Shutdown | Shutdown the cluster
    delegate_to: localhost
    ansible.builtin.command: talosctl {{ talosctl_opts }} shutdown
