---

- hosts: controlplane
  gather_facts: no
  become: false
  run_once: true
  tasks:
  - name: Sidero | Set facts
    set_fact:
      sidero_metallb_manifest: ../manifests/sidero-metallb.service.yaml
      clusterctl_manifests:
      - ../manifests/bootstrap.clusterctl.yaml
      - ../manifests/controlplante.clusterctl.yaml
      - ../manifests/infrastructure.clusterctl.yaml

  - name: Sidero | Check variables
    assert:
      fail_msg: The required env variables must be set
      that:
      - api_endpoint_ipaddr | length > 0
      - siderolink_endpoint_ipaddr | length > 0

  - name: Sidero | Create the resources using clusterctl
    with_items: "{{ clusterctl_manifests }}"
    delegate_to: localhost
    kubernetes.core.k8s:
      state: present
      src: "{{ item }}"

  - name: Sidero | Declare the Sidero Metal
    delegate_to: localhost
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: "cilium.io/v2alpha1"
        kind: CiliumLoadBalancerIPPool
        metadata:
          name: "core-pool"
          namespace: kube-system
        spec:
          blocks:
          - cidr: "{{ siderolink_endpoint_ipaddr }}"
          - cidr: "{{ api_endpoint_ipaddr }}"
          serviceSelector:
            matchLabels:
              "serviceType": "sidero-metal"

  - name: Sidero | Patch the services to use Cilium L2
    delegate_to: localhost
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: "{{ item.name }}"
          namespace: sidero-system
          labels:
            serviceType: sidero-metal
        spec:
          ports:
          - port: "{{ item.port }}"
            targetPort: "{{ item.port }}"
          selector:
            app: sidero
            control-plane: sidero-controller-manager
          type: LoadBalancer
    with_items:
    - name: sidero-webhook
      port: 443
    - name: sidero-http
      port: 8081
      cluster_ip: "{{ api_endpoint_ipaddr }}"
    - name: sidero-dhcp
      port: 67
    - name: sidero-tftp
      port: 69
    - name: sidero-siderolink
      port: 51821
      cluster_ip: "{{ siderolink_endpoint_ipaddr }}"
