- name: Create a network
  delegate_to: localhost
  run_once: true
  block:
  - name: Check the network
    ansible.builtin.command: virsh net-info {{ item.name }}
    register: exists
    changed_when: false
    failed_when: false

  - when: exists.stdout_lines | length == 0
    block:
    - name: Define a new network
      connection: local
      template:
        src: "{{ inventory_dir }}/day-0/templates/libvirt-net.xml.j2"
        dest: /tmp/libvirt-{{ item.name }}.xml
        remote_src: false

    - name: Create a new network
      register: result
      ansible.builtin.command: virsh net-create /tmp/libvirt-{{ item.name }}.xml

    - name: Delete temporary files
      ansible.builtin.file:
        path: /tmp/libvirt-{{ item.name }}.xml
        state: absent
