- name: Libvirt | Create a network
  delegate_to: localhost
  run_once: true
  block:
  - name: Libvirt | Check the network
    ansible.builtin.command: virsh net-info {{ item.name }}
    register: exists
    changed_when: false
    failed_when: false

  - when:
    - exists.stdout_lines | length == 0
    - item.name != "default"
    block:
    - name: Libvirt | Define a new network
      connection: local
      template:
        src: "{{ inventory_dir }}/day-0/templates/libvirt-net.xml.j2"
        dest: /tmp/libvirt-{{ item.name }}.xml
        remote_src: false

    - name: Libvirt | Create a new network
      ansible.builtin.command: virsh net-create /tmp/libvirt-{{ item.name }}.xml

    - name: Libvirt | Delete temporary files
      ansible.builtin.file:
        path: /tmp/libvirt-{{ item.name }}.xml
        state: absent
