- name: Configuration generation | Set facts
  set_fact:
    patch_dir: '{{ inventory_dir }}/day-1/patchs'

- name: Configuration generation | Create host patch
  block:
  - name: Configuration generation | Create the host patch file
    delegate_to: localhost
    ansible.builtin.copy:
      content: '{{ machine_patch }}'
      dest: '{{ patch_dir }}/{{ inventory_hostname }}.host.yaml'

  - name: Configuration generation | Create talos configuration for each node
    delegate_to: localhost
    ansible.builtin.command: |
      talosctl machineconfig patch {{ inventory_dir }}/{{ generic_machineconfig }} \
        --patch @{{ patch_dir }}/{{ inventory_hostname }}.host.yaml \
        -o {{ inventory_dir }}/{{ inventory_hostname }}.host.yaml
