apiVersion: v1
kind: Namespace
metadata:
  name: testing
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: nginx
  name: nginx-pv-claim
  namespace: testing
spec:
  storageClassName: openebs-hostpath
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: testing
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:1.16.1-alpine
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /var/lib/nginx
          name: nginx-pv-claim
      volumes:
      - name: nginx-pv-claim
        persistentVolumeClaim:
          claimName: nginx-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: testing
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: nginx
  type: LoadBalancer