---
apiVersion: v1
kind: Service
metadata:
  name: "{{ item.name }}"
  namespace: sidero-system
{% if cluster_ip if defined %}
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ cluster_ip }}
{% else %}
    metallb.universe.tf/address-pool: {{ ipaddr_pool_name }}
{% endif %}
spec:
  ports:
  - port: "{{ item.port }}"
    targetPort: "{{ item.port }}"
  selector:
    app: sidero
    control-plane: sidero-controller-manager
  type: LoadBalancer
