- hosts: all
  gather_facts: no
  become: false
  serial: 1

  vars:
    adding_node: true

  tasks:
  - name: Adding new nodes | Get cluster members
    changed_when: false
    failed_when: members.stdout_lines | length == 0
    delegate_to: localhost
    register: members
    ansible.builtin.shell:
      cmd: |
        set -o pipefail
        kubectl get nodes -o wide | awk '{print $6}'

  - name: Adding new nodes | Setting facts
    set_fact:
      nodes: '{{ members.stdout_lines | to_yaml }}'

  - name: Adding new nodes | Configuring if not a member yet
    when: not inventory_hostname in nodes
    block:
    - name: Adding new nodes | Configuring the new node
      include_tasks: '{{ inventory_dir }}/tasks/gen-host-conf.yml'

    - name: Adding new nodes | Applying configuration
      include_tasks: '{{ inventory_dir }}/tasks/apply-host-conf.yml'
