- hosts: all
  gather_facts: no
  become: false
  serial: 1

  tasks:
  - name: Removing nodes | Get cluster members
    changed_when: false
    failed_when: members.stdout_lines | length == 0
    delegate_to: localhost
    register: members
    run_once: true
    ansible.builtin.command: kubectl get nodes -o=jsonpath='{.items..status.addresses[?(@.type=="InternalIP")].address}'

  - name: Removing nodes | Check cluster members
    assert:
      that: members.stdout | length > 0
      fail_msg: No node found using 'kubectl get nodes', please check your cluster.

  - name: Removing nodes | Setting facts
    set_fact:
      inventory_nodes: '{{ groups["all"] }}'
      running_nodes: '{{ members.stdout | split(" ") }}'
      talosctl_opts: --talosconfig {{ inventory_dir }}/talosconfig

  - name: Removing nodes | Remove the node if not part of the inventory anymore
    with_items: '{{ running_nodes }}'
    when: item not in inventory_nodes
    include_tasks: '{{ inventory_dir }}/tasks/remove-node.yml'

